# Generated by Django 3.1.2 on 2022-06-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adhar_Number', models.IntegerField(max_length=12)),
                ('Pan_Number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
